# This Action builds the documentation site in mkdocs, and pushes it to the gh-pages branch, from where it is deployed

name: build-and-deploy-to-gh-pages.yml
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force # Output files are force-pushed to gh-pages branch